### ISSUE TITLE
Why not dotnet_diagnostic.xxxxxxxx.severity=none

### ISSUE THREAD

**Issue by p-bojkowski** [mykolav/require-named-args-fs#4]
Hi :)

good work @mykolav ! thx!!!
Wouldn't it be better if it were configurable?

dotnet_diagnostic.xxxxxxxx.severity=none

**Comment by mykolav** [comment]
Hi :)

Thank you for the kind words!

It's a great idea, I'll look into it. But unfortunately cannot give even an approximate timeline at the moment.
If you're asking because you're considering making a PR, that's definitely welcome.

**Comment by mykolav** [comment]
Hey, @p-bojkowski 

So, I had a chance to spend some time on your question. And as it turns out, starting in Visual Studio 2019 version 16.3, you can [configure the severity of analyzer rules, or diagnostics](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-severity-levels), in an EditorConfig file, from the light bulb menu, and the error list.

Add the following to the `[*.cs]` section of your .editorconfig.

```ini
[*.cs]
dotnet_diagnostic.RequireNamedArgs.severity = error
```

The possible severity values are:
- `error`
- `warning`
- `suggestion`
- `silent`
- `none`
- `default` (in case of this analyzer, it's equal to `error`)

Please take a look at [the documentation](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-severity-levels) for a detailed description.

I'll add a corresponding section to the README.md.
